# Generated by Django 6.0.6 on 2026-06-20 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_file', models.ImageField(upload_to='templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_x', models.IntegerField(default=400)),
                ('name_y', models.IntegerField(default=300)),
                ('name_font_size', models.IntegerField(default=40)),
                ('name_color', models.CharField(default='#1a1a2e', max_length=20)),
                ('event_x', models.IntegerField(default=400)),
                ('event_y', models.IntegerField(default=380)),
                ('event_font_size', models.IntegerField(default=24)),
                ('date_x', models.IntegerField(default=400)),
                ('date_y', models.IntegerField(default=430)),
                ('date_font_size', models.IntegerField(default=18)),
                ('cert_id_x', models.IntegerField(default=100)),
                ('cert_id_y', models.IntegerField(default=520)),
                ('cert_id_font_size', models.IntegerField(default=12)),
                ('qr_x', models.IntegerField(default=700)),
                ('qr_y', models.IntegerField(default=470)),
                ('qr_size', models.IntegerField(default=80)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('organizer', models.CharField(max_length=255)),
                ('certificate_type', models.CharField(choices=[('participation', 'Participation'), ('completion', 'Completion'), ('achievement', 'Achievement'), ('internship', 'Internship'), ('appreciation', 'Appreciation')], default='participation', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(blank=True, max_length=255)),
                ('course', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.event')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(default='valid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.participant')),
            ],
        ),
    ]
